function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
"___________ is killing esports.",
"We make ________ and then defense it.",
"Slasher just leaked __________",
"#SAVE________",
"Tahts ______, don’t worry.",
"Richard Lewis’ ego is bigger than __________",
"__________ OP",
"We should see a _______ anytime now",
"Loco Doco was caught on stream __________",
"I drank so much Dr Pepper at MLG I __________ into _________",
"IPL6 was canceled because of _________",
"SO MANY _____________!!",
"___________, The Savior of E-sports.",
"We knew e-sports would be a thing once we saw #__________ trending on Twitter.",
"My favorite thing to do at MLG is to pretend I am _________.",
"When I made ______ he should have made ______.  But he didn’t and won.  That’s why he’s a terrible player.",
"_______ is very useful to have.",

"DJ Wheat had to leave MLG due to _______________.",
"Stephano joked on stream about ___________ to a ___________",
"I placed a side bet that __________ would ________",
"I got in a twitter feud with Jessica over __________",
"The secret to Koreans success in esports is  __________",
"__________ started a kickstarter for __________",
"The real person behind #ESPORTSPROBLEMS is ____________",
"Do you think the moon is really made of _________ ?",
"____________ #1 seed",
"Blizzards next project is an MMO based on ____________",
"On new year's eve I got drunk and _______________",
"orangemilkis quit esports because of _____________",
"The best rivalry in esports is between ____________ and ___________",
"___________ no fluff",
"Can you believe that Silverfire ate __________ for dinner?",
"Have you heard about Adibesi's new gig observing ___________?",
"I finally have enough eSports dollars to buy __________?",
"__________ is someone who is always Mafia.",
"You could subsitute korean commentators with __________ and I would never know the diffrence.",
"I present to you, your MLG Champion __________. ",
"I can't believe that ________ is #1 on reddit right now.",
"EG just picked up _________",
"We gave Carlton caffene and now he is _________",
"I just saw DRG's __________ in the bathroom",
"Why on earth is that girl cosplaying as _________?",
"Counter Strike 1.6 players are up in arms about _________",
"This week Chanman will have ______ as a guest on Climbing the Ladder",
"All that ever gets done at TL HQ is ________",
"Slayers Boxer really retired from profesional play because of ________",
"Two halo players just got into a fist fight over ________",
"Destiny's latest blog is 82,000 words on _________",
"Thanks to _________ Korea is boycotting NASL again",
"Today Naniwa made an ass out of himself, again, when he __________",
"Twitch TV just goe a new set of chat icons that resemble ___________",
"It must take a bunch of work to get ________ looking that good",
"Did you catch the VOD of tobiwan freaking out over ________",
"Team liquid gave themselves the award for ___________, again.",
"I have the weirdest boner for ________",
"I just had a 30 minute conversation with Day[9] about _______",

"__________ was/were more interesting than Liquid Rising.",
"___________ but at what cost",
  ];
}

function white() {
  return [
   "$8.95",
"#ESPORTSPROBLEMS",
"#GSL",
"5 Rax Reapers",
"8mmspikes",
"Abuzucom",
"Angel Munoz",
"APM",
"Applying for WCG Ultimate Gamer",
"Artosis Pylon",
"Artosis’ Baby",
"Ashe",
"Bitter quake players",
"Black Hole",
"Boxer actually wears briefs",
"Broaches and Brofesters",
"Brony",
"Brood War Elitism",
"Bubble Bubble Pop Pop",
"CGS",
"Combat Ex",
"cs 1..6",
"cs go",
"Day[9] masturbating in an airplane",
"Dead Game",
"Destiny’s penis",
"Destructible Rocks",
"Discussing collusion at Jimmie Johns®",
"djWHEATJeans",
"Drow Ranger ",
"Dyrus’ pillow",
"E-sports Journalism",
"Edward Starcraft",
"ESPORTS",
"eSports chicken and waffles ",
"eSports dollars",
"Extended series",
"Flash’s ruler",
"Flipz Girls",
"FrankerZ (not e-sports per say...but)",
"Fraud",
"Getting mugged in China",
"Glorious PC Master Race",
"Gus Ledesma",
"Gwin",
"Hallucinated Void Rays",
"hot_bid photobombs",
"I'm not mafia",
"Illuminati",
"Jinro’s chin",
"John the Translator",
"JP's beta male mannerisms ",
"Justin Wong",
"Khaldor’s bulging biceps",
"KPOP",
"Lag",
"Leafeator's hair",
"Lindsey Sporrer",
"Look No Hands",
"Mia Rose",
"Mike Ross",
"My ex-wife Linda",
"My Murloc Impersonation",
"NASL Sound Guy",
"Nerd Rage",
"One angry leather jacket",
"Over 100,000 concurrent viewers",
"Piratebird",
"Pro-Ho",
"Probes and pylons",
"Rage Quit",
"Release day server problems",
"Robbie, the angry drunk",
"Rosco's Chicken and Waffles",
"RSI",
"l",
"Slayers Jessica",
"Sleeping 8 people to a room",
"Soon™",
"Soooooooo many banelings",
"Special Tactics",
"Stream Sniping",
"T-shirt and sports coat",
"Teemo",
"That one drunken episode of SOTG that was never released",
"the BEFORE TIME",
"The Evil Genius’ Curse",
"THEGUNRUN",
"Tons of Damage",
"Twitch Turbo",
"Twitch TV Chat Smileys",
"Valve time",
"Wicker basket",
"Lens flare",
"Dick pics",
"@LiquidRet",
"Liquid`Polt",
"AMERICA",
"WCS",
"Chicken and Waffles",
  ];
}

exports.getDeck = getDeck;
